### ISSUE TITLE
What is the status of this package.

### ISSUE THREAD

**Issue by drnkwati** [yangxikun/php-simple-html-purify#1]
Hi
First of all good job to the developer Yang.
I could not find a light weight alternative to htmlpurifier.
This one comes pretty close with a different approach but am concerned
as it was last updated since it 3rd commit in 2016.
So my question is this package actively maintained or should i look for another.
thanks

**Comment by yangxikun** [comment]
Hello @drnkwati , This project is still under maintained.
I had researched htmlpurifier, but it's complex and doesn't meet my requirement.

**Comment by drnkwati** [comment]
I will love to contribute.
 Itried using this package but found potential injection valnorabilities.
Check this
https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet
https://html5sec.org/

**Comment by yangxikun** [comment]
This package doesn't apply any xss filter rules. you need to define the rules.
