### ISSUE TITLE
How to allow only spercific style attributes and values

### ISSUE THREAD

**Issue by drnkwati** [yangxikun/php-simple-html-purify#3]
I want to allow a specific set of style attribute on all elements but cant get it working.
Is it possible if so I will appreciate any help with a regex that accomplish this.
example this:
`$dirtyHtml = '<div class="test" style="align-content: center; background-image: url("paper.gif");"></div>';`

after purify becomes becomes:
`$cleanHtml = '<div class="test" style="background-image: url("paper.gif");"></div>';`

how can i accomplish this?
Can i allow a specific set of style attributes? 
Can i allow a specific set of style values for a given attribute?

thanks

**Comment by yangxikun** [comment]
Please see `tests/AttrWhiteListTest.php` and `tests/AttrValueWhiteListTest.php`

**Comment by drnkwati** [comment]
Not helpful,
I still cant allow specific CSS attribute value pair.

**Comment by xikunyang** [comment]
Can you give me some test code?

**Comment by yangxikun** [comment]
Can you give me some test code?

**Comment by drnkwati** [comment]
> example:
> `$dirtyHtml = '<div class="test" style="align-content: center; background-image: url("paper.gif");"></div>';`
> 
> after purify becomes becomes:
> `$cleanHtml = '<div class="test" style="background-image: url("paper.gif");"></div>';`
> 
> how can i accomplish this?
> Can i allow a specific set of style attributes?
> Can i allow a specific set of style values for a given attribute?
> 
> thanks
